In [43]:
import pandas as pd

In [11]:
import requests
prefix = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/"
url = prefix + 'yellow_tripdata_2021-01.csv.gz'
# 这里的 verify=False 会跳过证书检查
response = requests.get(url, verify=False)

with open('yellow_tripdata_2021-01.csv.gz', 'wb') as f:
    f.write(response.content)

# 下载完成后再用 pandas 读取本地文件
df = pd.read_csv('yellow_tripdata_2021-01.csv.gz', nrows=100)
df.head()

/Users/weiaozhang/Desktop/Docker_workshop/data-engineering-docker-workshop/pipeline/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/weiaozhang/Desktop/Docker_workshop/data-engineering-docker-workshop/pipeline/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [23]:
df[["tpep_dropoff_datetime"]].iloc[1]

tpep_dropoff_datetime    2021-01-01 00:52:19
Name: 1, dtype: object

In [25]:
# Specify data types for each column
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    'yellow_tripdata_2021-01.csv.gz',
    nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               100 non-null    Int64
 1   tpep_pickup_datetime   100 non-null    datetime64[ns]
 2   tpep_dropoff_datetime  100 non-null    datetime64[ns]
 3   passenger_count        100 non-null    Int64
 4   trip_distance          100 non-null    float64
 5   RatecodeID             100 non-null    Int64
 6   store_and_fwd_flag     100 non-null    string
 7   PULocationID           100 non-null    Int64
 8   DOLocationID           100 non-null    Int64
 9   payment_type           100 non-null    Int64
 10  fare_amount            100 non-null    float64
 11  extra                  100 non-null    float64
 12  mta_tax                100 non-null    float64
 13  tip_amount             100 non-null    float64
 14  tolls_amount           100 non-null    float64
 15  improvement_surcharge  100 non-null    float64
 16  total_amount           100 non-null    float64
 17  congestion_surcharge   100 non-null    float64
dtypes: Int64(6), datetime64[ns](2), float64(9), string(1)
memory usage: 14.8 KB

In [27]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [28]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [29]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [30]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [31]:
len(df)

100

In [37]:
df_iter = pd.read_csv(
    
    'yellow_tripdata_2021-01.csv.gz',
    dtype = dtype,
    parse_dates = parse_dates,
    iterator = True,
    chunksize = 100000
    
)

In [38]:
#checking number of lines of data in one chunk plus number of chunks looping through.
for i in df_iter:
    print(len(i))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [39]:
from tqdm.auto import tqdm

In [42]:
df_iter = pd.read_csv(
    
    'yellow_tripdata_2021-01.csv.gz',
    dtype = dtype,
    parse_dates = parse_dates,
    iterator = True,
    chunksize = 100000
    
)

for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name = "yellow_taxi_data", con = engine, if_exists = 'append')

0it [00:00, ?it/s]

In [ ]:
target_table = 'yellow_taxi_data'

first = True
for df_chunk in tqdm(df_iter):
    
    if first:
        df_chunk.head(0).to_sql(name = target_table, con = engine, if_exists = 'replace')        
        first = False
    
    df_chunk.to_sql(name = target_table, con = engine, if_exists = 'append')

In [ ]:
#!/usr/bin/env python
# coding: utf-8


import pandas as pd
import requests
from tqdm.auto import tqdm
import argparse
from sqlalchemy import create_engine

pg_user = 'root'
pg_pass = 'root'
pg_host = 'localhost'
pg_port = 5432
pg_db = 'ny_taxi'

year = 2021
month = 1

table_name = 'yellow_taxi_data'
target_table = 'yellow_taxi_data'
prefix = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/"
url = prefix + 'yellow_tripdata_2021-01.csv.gz'
csv_name = "yellow_tripdata_2021-01.csv.gz"

def main(params):
    user = params.pg_user
    password = params.pg_pass
    host = params.pg_host
    port = params.pg_port
    db = params.pg_db
    table_name = params.target_table
    url = params.url


    
# 这里的 verify=False 会跳过证书检查

    print(f"downloading yellow taxi data 2021/01: {url}...")
    response = requests.get(url, verify=False) 
    with open(csv_name, 'wb') as f:
        f.write(response.content)


# Specify data types for each column
    dtype = {
        "VendorID": "Int64",
        "passenger_count": "Int64",
        "trip_distance": "float64",
        "RatecodeID": "Int64",
        "store_and_fwd_flag": "string",
        "PULocationID": "Int64",
        "DOLocationID": "Int64",
        "payment_type": "Int64",
        "fare_amount": "float64",
        "extra": "float64",
        "mta_tax": "float64",
        "tip_amount": "float64",
        "tolls_amount": "float64",
        "improvement_surcharge": "float64",
        "total_amount": "float64",
        "congestion_surcharge": "float64"
    }
    
    parse_dates = [
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime"
    ]

    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
    
    df = pd.read_csv(
        'yellow_tripdata_2021-01.csv.gz',
        nrows=100,
        dtype=dtype,
        parse_dates=parse_dates
    )



    print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))



def run():
    df_iter = pd.read_csv(

        'yellow_tripdata_2021-01.csv.gz',
        dtype = dtype,
        parse_dates = parse_dates,
        iterator = True,
        chunksize = 100000

    )


    target_table = 'yellow_taxi_data'

    first = True
    for df_chunk in tqdm(df_iter):
        
        df_chunk.tpep_pickup_datetime = pd.to_datetime(df_chunk.tpep_pickup_datetime)
        df_chunk.tpep_dropoff_datetime = pd.to_datetime(df_chunk.tpep_dropoff_datetime)

        if first:
            df_chunk.head(0).to_sql(name = target_table, con = engine, if_exists = 'replace')        
            first = False
        
        df_chunk.to_sql(name = target_table, con = engine, if_exists = 'append')

if __name__ == "__main__":
    run()